 [![.github/workflows/android.yml](https://github.com/Abellujanm/android-sdk-sources-for-api-level-33/actions/workflows/android.yml/badge.svg)](https://github.com/Abellujanm/android-sdk-sources-for-api-level-33/actions/workflows/android.yml)           
 name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
